# Generated by Django 5.2 on 2025-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='latitude',
            field=models.FloatField(default=52.9229),
        ),
        migrations.AddField(
            model_name='busstop',
            name='longitude',
            field=models.FloatField(default=-1.4773),
        ),
    ]
